
alerting:
  ???:
    token: "<github-token>" # WARN: DO NOT CHANGE THIS LINE
# FILL IN THE MISSING VALUES ABOVE

# FILL IN THE MISSING VALUES BELOW
endpoints:
  - name: Leantime
    url: <leantime-url> # WARN: DO NOT CHANGE THIS LINE
    interval: 60s
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 300"
    alerts:
      - type: github
        failure-threshold: 3
        success-threshold: 5
        send-on-resolved: true
        description: "Sensei, Leantime is down! Please check and fix it."

  - name: Gatus
    url: <gatus-url> # WARN: DO NOT CHANGE THIS LINE
    interval: 60s
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 500"
    alerts:
      - type: github
        failure-threshold: 3
        success-threshold: 5
        send-on-resolved: true
        description: "Sensei, Gatus is down! Please check and fix it."
